name: cftc_fpt_34
description: Application du CFTC-FTP 34
# on ajout un name et une description
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3
#la version de l'appli
environment:
  sdk: ">=2.7.0 <3.0.0"
#version du sdk
dependencies:
  flutter:
    sdk: flutter
  #on utilisera le sdk de flutter pour compiler tout ça
  #Touts les packages que nous avons utilisé sont ici avec chacun sa propre version
  flutter_cache_manager: ^3.0.1
  splashscreen: ^1.3.5
  table_calendar: ^2.3.3
  flutter_speed_dial: ^3.0.5
  file_picker: ^3.0.1
  image_ink_well: ^0.1.0
  image_cropper: ^1.3.1
  url_launcher: ^6.0.3
  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0
  flutter_clean_calendar: ^1.0.2+1
  shared_preferences: ^2.0.5
  rename: ^1.2.0
  path_provider: ^2.0.1
  native_pdf_view: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

    #ajout d'une icone pour l'appli
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoappli.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #toutes les images et les pdf sont ici avec chacun son chemin relative
  assets:
    - assets/epsi.png
    - assets/macif.jpg
    - assets/mutuel.png
    - assets/prefon.jpg
    - assets/maladie.png
    - assets/agent.png
    - assets/logo.png
    - assets/logoappli.png
    - assets/protectionsocial.jpeg
    - assets/mongolfiere.jpeg
    - assets/voix-mars.png
    - assets/voix-juin.png
    - assets/voix-septembre.png
    - assets/rifseep.png
    - assets/cap.png
    - assets/collectivites.png
    - assets/egaliteprof.png
    - assets/enfant.png
    - assets/fonctionpublique.png
    - assets/deces.png
    - assets/police.png
    - assets/ultramarin.png
    - docMag/lavoix-mars.pdf
    - docMag/lavoix-septembre.pdf
    - docMag/lavoix-juin.pdf
    - docActu/protectionsociale-decembre.pdf
    - docActu/cap.pdf
    - docActu/reformeconges.pdf
    - docActu/enfantconverti.pdf
    - docActu/enfantdeceder.pdf
    - docActu/egalitecollectivites.pdf
    - docActu/policiersmunicipaux.pdf
    - docActu/fonctionpublique.pdf
    - docActu/rifseep.pdf
    - docActu/collect2020.pdf
    - docMaladie/maladie-2019.pdf
    - docAgent/agent.pdf
