name: cftc_fpt_34
description: Application du CFTC-FTP 34

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  splashscreen: ^1.3.5
  table_calendar: ^2.3.3
  flutter_speed_dial: ^1.2.5
  file_picker: ^1.9.0+1
  image_ink_well: ^0.1.0
  advance_pdf_viewer: any
  image_cropper: ^1.3.1
  url_launcher: ^5.2.7
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.11.0
  flutter_clean_calendar: ^1.0.2+1
  shared_preferences: ^0.5.12+4
  rename: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoappli.png"

flutter:
  uses-material-design: true

  assets:
    - assets/maladie.png
    - assets/agent.png
    - assets/logo.png
    - assets/logoappli.png
    - assets/protectionsocial.jpeg
    - assets/mongolfiere.jpeg
    - assets/voix-mars.png
    - assets/voix-juin.png
    - assets/voix-septembre.png
    - assets/rifseep.png
    - assets/cap.png
    - assets/collectivites.png
    - assets/egaliteprof.png
    - assets/enfant.png
    - assets/fonctionpublique.png
    - assets/deces.png
    - assets/police.png
    - assets/ultramarin.png
    - docMag/lavoix-mars.pdf
    - docMag/lavoix-septembre.pdf
    - docMag/lavoix-juin.pdf
    - docActu/protectionsociale-decembre.pdf
    - docActu/cap.pdf
    - docActu/reformeconges.pdf
    - docActu/enfantconverti.pdf
    - docActu/enfantdeceder.pdf
    - docActu/egalitecollectivites.pdf
    - docActu/policiersmunicipaux.pdf
    - docActu/fonctionpublique.pdf
    - docActu/rifseep.pdf
    - docActu/collect2020.pdf
    - docMaladie/maladie-2019.pdf
    - docAgent/agent.pdf
